version: "3"

services:
  db:
    # platform: linux/amd64
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${DEV_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DEV_MYSQL_DATABASE_NAME}
      MYSQL_USER: ${DEV_MYSQL_USER}
      MYSQL_PASSWORD: ${DEV_MYSQL_PASSWORD}
      MYSQL_MAX_ALLOWED_PACKET: 512M
    restart: unless-stopped
    ports:
      - "${DEV_MYSQL_PORT}:3306"
    volumes:
      - dbdata:/var/lib/mysql
  pma:
    # platform: linux/amd64
    image: phpmyadmin:latest
    container_name: pma
    environment:
      PMA_HOST: db
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 512M
    restart: always
    ports:
      - 8081:80
    links:
      - db
volumes:
  dbdata:
